n,a,b=map(int,input().split())
t=list(map(int,input().split()))
d=0
s=0
for i in range(n):
    if(t[i]==1):
        if(a==0):
            if(b==0):
                if(s==0):
                    d+=1
                else:
                    s-=1
            else:
                b-=1
                s+=1      
        else:
            a-=1
    else:
        if(b==0):
            d+=2
        else:
            b-=1
print(d)
