t=int(input())
for _ in range(t):
    n=int(input())
    s=list()
    for _ in range(n):
        a=input()
        s.append(a)
    u=int(s[n-2][n-1])
    d=int(s[1][0])
    l=int(s[n-1][n-2])
    r=int(s[0][1])
    c=0
    k=list()
    if(r+d==0):
        if(u==0):
            c+=1
            k.append(n-1)
            k.append(n)
        if(l==0):
            c+=1
            k.append(n)
            k.append(n-1)
    elif(r+d==2):
        if(u==1):
            c+=1
            k.append(n-1)
            k.append(n)
        if(l==1):
            c+=1
            k.append(n)
            k.append(n-1)
    else:
        if(l+u==2):
            if(r==1):
                c+=1
                k.append(1)
                k.append(2)
            if(d==1):
                c+=1
                k.append(2)
                k.append(1)
        elif(l+u==0):
            if(r==0):
                c+=1
                k.append(1)
                k.append(2)
            if(d==0):
                c+=1
                k.append(2)
                k.append(1)
        else:
            if(r==0):
                c+=1
                k.append(1)
                k.append(2)
            if(d==0):
                c+=1
                k.append(2)
                k.append(1)
            if(u==1):
                c+=1
                k.append(n-1)
                k.append(n)
            if(l==1):
                c+=1
                k.append(n)
                k.append(n-1)
    print(c)
    if(len(k)!=0):
        for i in range(0,len(k),2):
            print(k[i],k[i+1])
    
